FROM php:8.3-fpm

RUN apt-get update && \
    apt-get install -y git unzip libpng-dev libonig-dev libxml2-dev libzip-dev zip && \
    docker-php-ext-install pdo_mysql && \
    rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

CMD ["php-fpm"]
